<<<<<<< HEAD
# Welcome to Jekyll!

# Website settings
title: Andés González Sánchez
description: Jack's blog,use Jekyll and github pages.
keywords: 'Jack,Jalpc,blog,Jekyll,github,gh-pages'
baseurl: ''
url: 'http://andgosds.github.io'
# url: "http://127.0.0.1:4000"
img_path: '/static/img/blog'

# author
author:
  name: 'andgosds'
  first_name: 'Andrés'
  last_name: 'González Sánchez'
  email: 'andgosds@gmail.com'
  facebook_username: 'facebook_username'
  github_username: 'andgosds'
  avatar: '/static/img/landing/Foto carnet.jpg'
  desc: 'Soy un científico de datos en formación. Actualmente cursando el Master en Data Science y Big Data por la Universidad de Sevilla'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
=======
theme: jekyll-theme-cayman
>>>>>>> c9fd92b6bcafc5e4dd4559d9cfa7c07d203ecf22
